import type { Theme } from '../../types';

export const DEFAULT_THEMES: Theme[] = [
  {
    id: 'warm-paper',
    name: 'Warm Paper',
    bg: '#F8F4E8',
    text: '#3E3A31',
    border: '#E3DEC3',
    accent: '#8E7C5D',
    isDark: false,
  },
  {
    id: 'kindle',
    name: 'Kindle',
    bg: '#F5F1E6',
    text: '#2C2B29',
    border: '#DFDACB',
    accent: '#7F735F',
    isDark: false,
  },
  {
    id: 'sepia',
    name: 'Sepia',
    bg: '#F4ECD8',
    text: '#433422',
    border: '#DFD3B9',
    accent: '#A2845E',
    isDark: false,
  },
  {
    id: 'cream',
    name: 'Cream',
    bg: '#FFF8E7',
    text: '#3A352A',
    border: '#EFE3C3',
    accent: '#9E8A5E',
    isDark: false,
  },
  {
    id: 'dark',
    name: 'Dark Mode',
    bg: '#1E1E1E',
    text: '#E0E0E0',
    border: '#333333',
    accent: '#A78BFA',
    isDark: true,
  },
  {
    id: 'oled',
    name: 'OLED Black',
    bg: '#000000',
    text: '#D1D5DB',
    border: '#1F2937',
    accent: '#8B5CF6',
    isDark: true,
  },
  {
    id: 'forest-night',
    name: 'Forest Night',
    bg: '#14251C',
    text: '#D0E0D5',
    border: '#203A2B',
    accent: '#4ADE80',
    isDark: true,
  },
  {
    id: 'blue-night',
    name: 'Blue Night',
    bg: '#0F172A',
    text: '#E2E8F0',
    border: '#1E293B',
    accent: '#38BDF8',
    isDark: true,
  },
];
